import type { Blog } from '@portfolio/types';

export const blogs: Blog[] = [
  {
    id: 'blog-suchana-ai',
    slug: 'building-suchana-ai-nepal-notices-vector-search',
    title:
      'Building SuchanaAI: Indexing & Searching Nepal’s Government Notices at Scale',
    excerpt:
      'How we engineered SuchanaAI to ingest thousands of fragmented PDF circulars, run bilingual Devanagari OCR, and enable semantic vector search across Nepal’s public sector notices.',
    content:
      '# Building SuchanaAI: Indexing & Searching Nepal’s Government Notices at Scale\n\nIn Nepal, public sector notices, civil service openings (Lok Sewa Aayog), and ministerial circulars are published across dozens of disparate government portals. Most documents are uploaded as low-resolution scanned PDFs with non-standard Devanagari fonts or raw image bitmaps.\n\nFinding a single scholarship announcement or procurement tender historically meant opening fifteen browser tabs, refreshing slow servers, and manually scanning hundred-page Gazette issues. We built **SuchanaAI** to solve this problem by combining automated web crawling, multi-stage OCR pipelines, and semantic vector search.\n\n![SuchanaAI Architecture Pipeline](https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. The Ingestion Engine & PDF Extraction Pipeline\n\nThe primary engineering hurdle is not language modeling; it is data ingestion fidelity. Government circulars are rarely clean UTF-8 text. They consist of:\n- Pre-Unicode font encodings (Preeti, Kantipur) where glyph codes collide with English ASCII.\n- Photocopied and stamped sheets with skewed baselines and bleed-through ink.\n- Irregular tabular columns spanning multiple portrait and landscape pages.\n\n```typescript\n// Pipeline extraction contract\nexport interface NoticeDocument {\n  id: string;\n  sourceUrl: string;\n  ministry: string;\n  publishedDateBs: string;\n  rawText: string;\n  cleanText: string;\n  embeddings: number[];\n  ocrConfidence: number;\n}\n```\n\nTo handle this, our crawler feeds raw PDFs into an asynchronous Python worker pool orchestrated with FastAPI and Redis queues. We apply adaptive binarization, deskewing, and custom Unicode font transliteration before invoking Tesseract 5 with specialized Nepali language training sets.\n\n![Data Processing Flow](https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Bilingual Semantic Vector Search with pgvector\n\nKeyword matching in Devanagari often fails due to inflectional suffixes, spelling variations, and colloquial search terms. A user querying *"शिक्षक भर्ना"* (teacher recruitment) should match notices containing *"अध्यापन अनुमति पत्र"* (teaching license exam) or *"माध्यमिक तह दरबन्दी"*.\n\nWe utilize a dense retrieval architecture using multi-lingual sentence embeddings coupled with PostgreSQL\'s `pgvector` extension.\n\n```sql\n-- Hybrid semantic + full-text query in PostgreSQL\nSELECT \n  id, \n  title, \n  ministry, \n  published_date,\n  1 - (embedding <=> $1::vector) AS semantic_score,\n  ts_rank(tsv_body, plainto_tsquery(\'simple\', $2)) AS text_score\nFROM notices\nWHERE (1 - (embedding <=> $1::vector)) > 0.68\nORDER BY (semantic_score * 0.7 + text_score * 0.3) DESC\nLIMIT 20;\n```\n\nBy blending cosine distance from high-dimensional embeddings with lexical full-text ranks, SuchanaAI returns high-precision results within **45 milliseconds** across over 100,000 indexed documents.\n\n![Vector Search Visualization](https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Real-Time Indexing and Alert Subscriptions\n\nBeyond on-demand search, users can configure personalized alerts for specific ministries or keywords. When new notices are published:\n1. The crawler detects new PDF links via checksum diffing.\n2. Ingestion completes in under 30 seconds.\n3. Notification triggers match subscriber criteria and dispatch instant push notifications and WhatsApp summaries.\n\nEngineering SuchanaAI taught our team that applied AI is 90% systems design, robust data pipelines, and error resilience. Solving real information accessibility challenges in Nepal remains one of the most rewarding milestones in our engineering journey.',
    coverImage:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    tags: ['AI', 'Full-Stack', 'Next.js', 'PostgreSQL', 'Nepal'],
    published: true,
    featured: true,
    position: 0,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-03-15T09:00:00.000Z',
    updatedAt: '2026-03-15T09:00:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-suchana-1',
        url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
        alt: 'SuchanaAI architecture diagram and neural network search layout',
        caption: 'SuchanaAI ingest, OCR, and vector embedding pipeline',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-suchana-ai',
      },
      {
        id: 'img-suchana-2',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        alt: 'Server infrastructure and data pipeline processing server cluster',
        caption:
          'Asynchronous workers handling PDF parsing and OCR transliteration',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-suchana-ai',
      },
      {
        id: 'img-suchana-3',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
        alt: 'High speed database vector computation visualization',
        caption: 'Sub-50ms hybrid vector search across Devanagari corpus',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-suchana-ai',
      },
    ],
  },
  {
    id: 'blog-db-resilience',
    slug: 'architecting-zero-downtime-resilient-databases',
    title:
      'Architecting Zero-Downtime Databases with Prisma, Postgres & Connection Pooling',
    excerpt:
      'A deep dive into connection budgets, session mode vs transaction mode in PgBouncer, graceful retry loops, and schema migrations that never lock production tables.',
    content:
      "# Architecting Zero-Downtime Databases with Prisma, Postgres & Connection Pooling\n\nWhen building modern web applications with serverless runtimes or autoscaling container fleets, the database is almost always the first component to hit catastrophic resource exhaustion. Each serverless function invocation spinning up its own connection pool quickly exhausts PostgreSQL's `max_connections` limit, resulting in connection refusal errors and 500 downtime.\n\nIn this article, we break down how to design a production-grade persistence tier using Prisma ORM, Supabase/AWS RDS PostgreSQL, and dedicated PgBouncer connection pooling.\n\n![Database Architecture Diagram](https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. The Connection Budget Formula\n\nPostgreSQL processes each active client connection inside a dedicated OS process. Allocating hundreds of idle connections wastes server RAM and incurs heavy context-switching penalties on CPU cores.\n\n```\nPool Budget = (Available RAM - OS Reserve) / (Work Mem + Buffer Overhead)\nIdeal Pool Size = (Core Count * 2) + Effective Spindle Count\n```\n\nIn serverless environments (Next.js App Router on Vercel or AWS Lambda), every cold start creates new connection attempts. To safeguard the database:\n1. **Transaction Pooling (Port 6543)** is used for all transient reads and standard transactional mutations.\n2. **Session / Direct Connection (Port 5432)** is strictly reserved for migrations (`prisma migrate`), LISTEN/NOTIFY, or advisory locks.\n\n![Connection Pooling Flowchart](https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Implementing Resilient Retry Logic in Prisma\n\nTransient network blips, TCP timeouts, or database failovers should not trigger user-facing errors. We wrap our data access layer in an intelligent retry wrapper that distinguishes transient connection drops from deterministic constraint violations.\n\n```typescript\nexport async function withTransientRetry<T>(\n  operation: () => Promise<T>,\n  retries = 2,\n  delayMs = 150,\n): Promise<T> {\n  try {\n    return await operation();\n  } catch (error: any) {\n    const isTransient =\n      error.code === 'P1001' || // Can't reach database server\n      error.code === 'P1002' || // Database server timed out\n      error.code === 'P1017' || // Server closed the connection\n      error.message?.includes('Connection terminated unexpectedly');\n\n    if (isTransient && retries > 0) {\n      await new Promise((resolve) => setTimeout(resolve, delayMs));\n      return withTransientRetry(operation, retries - 1, delayMs * 2);\n    }\n    throw error;\n  }\n}\n```\n\n![Monitoring Database Metrics](https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Zero-Lock Schema Migration Strategy\n\nRunning `ALTER TABLE ADD COLUMN ... DEFAULT` on tables with millions of rows can acquire an exclusive table lock (`ACCESS EXCLUSIVE`), halting all write operations.\n\n### Safe Migration Best Practices:\n- **Add columns as nullable first** without default values.\n- **Backfill existing rows** in small batches via background worker jobs.\n- **Set default values and NOT NULL constraints** only after backfilling is complete.\n- **Always build indexes concurrently**: `CREATE INDEX CONCURRENTLY`.\n\nBy adhering to these principles, our systems maintain **99.99% uptime** across high-throughput production releases.",
    coverImage:
      'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Database', 'PostgreSQL', 'Prisma', 'Backend', 'Architecture'],
    published: true,
    featured: true,
    position: 1,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-03-08T11:30:00.000Z',
    updatedAt: '2026-03-08T11:30:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-db-1',
        url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',
        alt: 'Database cluster and data center servers',
        caption: 'Resilient PostgreSQL pooling with PgBouncer',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-db-resilience',
      },
      {
        id: 'img-db-2',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        alt: 'Analytics dashboard and database monitoring metrics',
        caption: 'Real-time connection throughput and query telemetry',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-db-resilience',
      },
      {
        id: 'img-db-3',
        url: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80',
        alt: 'Modern code development and database architecture interface',
        caption: 'Prisma schema synchronization and zero-downtime migrations',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-db-resilience',
      },
    ],
  },
  {
    id: 'blog-nextjs-16-deep-dive',
    slug: 'deep-dive-nextjs-16-app-router-turbopack',
    title:
      'Next.js 16 App Router Under the Hood: Turbopack, Streaming RSC & Partial Prerendering',
    excerpt:
      'An architectural dissection of React 19 Server Components, streaming hydration boundaries, and Turbopack compiler optimizations in Next.js 16.',
    content:
      "# Next.js 16 App Router Under the Hood: Turbopack, Streaming RSC & Partial Prerendering\n\nNext.js 16 marks a major paradigm shift in full-stack web development. With native support for React 19 primitives, persistent server cache primitives, and Rust-based Turbopack builds, frontend engineering is entering an era of sub-second builds and instant time-to-first-byte (TTFB).\n\nLet's dive beneath the surface abstractions to inspect how compilation, data fetching, and streaming execution work in production.\n\n![Next.js Architecture Diagram](https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. React Server Components (RSC) Wire Format\n\nWhen a browser navigates to a route, Next.js does not return monolithic HTML or pure JSON. It streams an optimized RSC payload containing:\n- Virtual DOM nodes for Server Components.\n- Module references for Client Components (`\"use client\"`).\n- Serialized props and streaming suspense boundaries.\n\n```typescript\n// Server Component streaming shell\nimport { Suspense } from 'react';\nimport { ProjectDetails } from './project-details';\nimport { SkeletonLoader } from '@/components/ui/skeleton';\n\nexport default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params; // Next.js 16 asynchronous params contract\n\n  return (\n    <main className=\"project-container\">\n      <header className=\"static-header\">\n        <h1>Project Overview</h1>\n      </header>\n      <Suspense fallback={<SkeletonLoader count={4} />}>\n        <ProjectDetails slug={slug} />\n      </Suspense>\n    </main>\n  );\n}\n```\n\nThe static header renders immediately into the initial TCP response packet, while the dynamic `ProjectDetails` stream chunks down the wire as soon as database queries resolve.\n\n![Performance Waterfall Analysis](https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Dynamic IO and Partial Prerendering (PPR)\n\nPartial Prerendering bridges the gap between static site generation (SSG) and dynamic SSR:\n- The static outer layout is pre-rendered at build time and cached globally at edge CDN nodes.\n- Dynamic holes wrapped in React `<Suspense>` stream in parallel over the same persistent HTTP connection.\n\n| Strategy | TTFB | Dynamic Data | Edge Cacheable |\n| :--- | :--- | :--- | :--- |\n| Pure SSR | 350ms - 800ms | Real-time | No |\n| Pure SSG | 15ms - 40ms | Stale until rebuild | Yes |\n| **PPR (Next.js 16)** | **18ms - 35ms** | **Instant Real-time Streams** | **Yes (Static Shell)** |\n\n![Turbopack Compilation Speed](https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Best Practices for Production Stability\n\n1. **Keep Client Boundaries at the Leaves**: Never mark an entire page file with `\"use client\"`. Keep data fetching on the server and pass minimal props into client leaf widgets.\n2. **Avoid Cascading Waterfalls**: Use `Promise.all()` or parallel RSC components to fetch independent data sources concurrently.\n3. **Adopt Cache Tags**: Invalidate specific views instantly using `revalidateTag('blogs')` without busting global caches.",
    coverImage:
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    tags: ['Next.js', 'React', 'TypeScript', 'Frontend', 'Web Development'],
    published: true,
    featured: true,
    position: 2,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-03-01T14:00:00.000Z',
    updatedAt: '2026-03-01T14:00:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-next-1',
        url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        alt: 'Code editor showing modern Next.js React TypeScript codebase',
        caption: 'Next.js 16 App Router compiler and server runtime',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-nextjs-16-deep-dive',
      },
      {
        id: 'img-next-2',
        url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
        alt: 'Core Web Vitals performance charts and metrics',
        caption: 'Streaming hydration and sub-20ms TTFB rendering curves',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-nextjs-16-deep-dive',
      },
      {
        id: 'img-next-3',
        url: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1200&q=80',
        alt: 'Modern development workflow and developer workspace',
        caption: 'Turbopack hot module reloading and build benchmarks',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-nextjs-16-deep-dive',
      },
    ],
  },
  {
    id: 'blog-mcp-ai-publishing',
    slug: 'autonomous-ai-publishing-with-mcp-and-scoped-keys',
    title:
      'Designing Resilient AI Publishing Agents with Model Context Protocol (MCP) & Scoped Keys',
    excerpt:
      'How we built a secure stdio and HTTP Model Context Protocol (MCP) publishing server that allows AI coding assistants to draft, review, and schedule CMS articles safely.',
    content:
      "# Designing Resilient AI Publishing Agents with Model Context Protocol (MCP) & Scoped Keys\n\nThe emergence of the **Model Context Protocol (MCP)** by Anthropic and open ecosystem tooling has enabled AI assistants (like Claude, Cursor, and custom agent loops) to move from passive autocomplete to active pair programmers capable of calling structured API tools directly.\n\nIn this article, we explore the architecture of our `@portfolio/mcp` server, which enables autonomous drafting, content auditing, and publishing while maintaining strict authorization boundaries.\n\n![AI Agent Automation Interface](https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. The MCP Tool Contract\n\nAn MCP server exposes standardized tools via JSON-RPC over `stdio` or SSE. Our server exports tools for:\n- `draft_blog`: Creates a draft article with markdown body and tags.\n- `update_blog`: Modifies an existing draft with optimistic concurrency locking.\n- `schedule_blog`: Enqueues an article for automatic publication at a designated future instant.\n- `list_media`: Queries available image assets in Supabase Storage.\n\n```typescript\n// MCP Tool Registration Definition\nexport const draftBlogTool = {\n  name: 'draft_blog',\n  description: 'Drafts a new blog post in the portfolio CMS',\n  inputSchema: {\n    type: 'object',\n    properties: {\n      title: { type: 'string', description: 'Article title' },\n      content: { type: 'string', description: 'Full Markdown content' },\n      tags: { type: 'array', items: { type: 'string' } },\n      excerpt: { type: 'string' },\n    },\n    required: ['title', 'content', 'tags'],\n  },\n};\n```\n\n![Security Architecture Flow](https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Scoped API Key Authentication (`pf_live_*`)\n\nGiving an autonomous agent full admin credentials is a massive security hazard. Instead, we issue scoped API keys prefixed with `pf_live_`:\n- **Cryptographic Hashing**: Keys are generated with 256 bits of entropy and stored in the database exclusively as Argon2/SHA-256 hashes.\n- **Granular Scopes**: `blogs:draft`, `blogs:publish`, `media:upload`, `projects:read`.\n- **Automatic Audit Trail**: Every write operation records the exact Actor ID, timestamp, IP address, and changed fields.\n\n```typescript\n// API Scope Guard in NestJS\n@Injectable()\nexport class ScopeGuard implements CanActivate {\n  constructor(private reflector: Reflector) {}\n\n  canActivate(context: ExecutionContext): boolean {\n    const requiredScopes = this.reflector.get<string[]>('scopes', context.getHandler());\n    const request = context.switchToHttp().getRequest();\n    const key = request.publisherKey;\n\n    if (!key || !requiredScopes.every((scope) => key.scopes.includes(scope))) {\n      throw new ForbiddenException('Insufficient publisher key permissions.');\n    }\n    return true;\n  }\n}\n```\n\n![AI Agent Workflow Diagram](https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Human-in-the-Loop Safety\n\nEven with autonomous drafting capabilities, our publishing protocol mandates:\n1. All AI-originated content is marked with `createdByAI: true`.\n2. Content defaults to `DRAFT` status.\n3. Final publication requires either explicit admin approval or pre-authorized scheduled release times.\n\nThis architecture delivers high velocity while guaranteeing that human editorial standards and security controls are never bypassed.",
    coverImage:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
    tags: ['AI', 'MCP', 'TypeScript', 'Security', 'Architecture'],
    published: true,
    featured: true,
    position: 3,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-02-22T10:15:00.000Z',
    updatedAt: '2026-02-22T10:15:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-mcp-1',
        url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
        alt: 'Futuristic AI neural network visual representation',
        caption: 'Model Context Protocol tool execution flow',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-mcp-ai-publishing',
      },
      {
        id: 'img-mcp-2',
        url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
        alt: 'Cybersecurity lock and cryptography concepts',
        caption:
          'Argon2 hashed scoped publisher keys and authorization boundaries',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-mcp-ai-publishing',
      },
      {
        id: 'img-mcp-3',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
        alt: 'Abstract digital workflows and automated data streams',
        caption: 'Audit trails and autonomous agent execution logs',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-mcp-ai-publishing',
      },
    ],
  },
  {
    id: 'blog-gsap-smooth-motion',
    slug: 'crafting-60fps-smooth-motion-gsap-scrolltrigger',
    title:
      'Mastering 60FPS Web Animation: GSAP, ScrollTrigger & Hardware Acceleration',
    excerpt:
      'A masterclass on building silky-smooth, GPU-accelerated motion systems in React, avoiding layout thrashing, and respecting prefers-reduced-motion.',
    content:
      "# Mastering 60FPS Web Animation: GSAP, ScrollTrigger & Hardware Acceleration\n\nNothing breaks the immersion of a digital portfolio faster than stuttering scroll animations, frame drops, or janky element reflows. To craft an experience that feels fluid and tactile, animations must run at a consistent 60 or 120 FPS by delegating transformation matrices directly to the GPU.\n\nIn this guide, we break down the physics and engineering behind our custom motion engine built with GSAP, ScrollTrigger, and Lenis smooth scrolling.\n\n![Fluid Motion and UI Design](https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. Avoiding Layout Thrashing: Composite-Only Properties\n\nThe browser rendering pipeline comprises four phases: **JavaScript → Style Calculation → Layout (Reflow) → Paint → Compositing**.\n\nAnimating properties like `top`, `left`, `height`, or `margin` forces the browser to recalculate the layout geometry of the entire DOM tree on every single frame:\n\n```css\n/* ❌ AVOIDS: Forces CPU layout recalculations */\n.card-bad {\n  transition: top 0.3s ease, width 0.3s ease;\n}\n\n/* ✅ PREFERRED: Promoted to GPU composite layer */\n.card-good {\n  will-change: transform, opacity;\n  transform: translate3d(0, var(--y), 0) scale(var(--scale));\n  transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1);\n}\n```\n\nBy restricting animations strictly to `transform` (translation, rotation, scale) and `opacity`, elements are rasterized into isolated GPU layers, completely bypassing the layout and paint stages.\n\n![GPU Hardware Acceleration Diagram](https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Choreographing Timelines with GSAP & ScrollTrigger\n\nFor complex section reveals, declarative CSS keyframes become unmaintainable. GSAP's timeline sequencer provides granular control over easing curves, stagger offsets, and scroll velocity pinning.\n\n```typescript\nimport gsap from 'gsap';\nimport { ScrollTrigger } from 'gsap/ScrollTrigger';\n\ngsap.registerPlugin(ScrollTrigger);\n\nexport function animateFeatureGrid(container: HTMLElement) {\n  const cards = container.querySelectorAll('.project-card');\n\n  return gsap.timeline({\n    scrollTrigger: {\n      trigger: container,\n      start: 'top 80%',\n      end: 'bottom 20%',\n      toggleActions: 'play none none reverse',\n    },\n  }).fromTo(\n    cards,\n    { y: 60, opacity: 0 },\n    {\n      y: 0,\n      opacity: 1,\n      duration: 0.85,\n      stagger: 0.12,\n      ease: 'power3.out',\n      clearProps: 'transform',\n    }\n  );\n}\n```\n\n![Frame Rate Performance Profiling](https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Accessibility & `prefers-reduced-motion`\n\nDelivering motion design responsibly means providing effortless opt-outs for visitors with vestibular disorders or motion sensitivities.\n\nOur application inspects the system media query and exposes a user-toggleable motion mode:\n- **Full**: Full dynamic physics, parallax depth, and cursor magnetic effects.\n- **Calm**: Instant opacity reveals, zero parallax drift, and standard cursor tracking.\n\n```typescript\nexport function isReducedMotion(): boolean {\n  if (typeof window === 'undefined') return false;\n  return (\n    window.matchMedia('(prefers-reduced-motion: reduce)').matches ||\n    document.documentElement.dataset.flow === 'calm'\n  );\n}\n```\n\nMotion is not decorative garnish; when applied with restraint and mechanical precision, it guides user attention and builds lasting digital delight.",
    coverImage:
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    tags: ['GSAP', 'CSS', 'Animation', 'UI/UX', 'Frontend'],
    published: true,
    featured: true,
    position: 4,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-02-14T16:45:00.000Z',
    updatedAt: '2026-02-14T16:45:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-gsap-1',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
        alt: 'Dynamic fluid visual motion elements and neon gradients',
        caption: 'High-performance interactive motion and easing physics',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-gsap-smooth-motion',
      },
      {
        id: 'img-gsap-2',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
        alt: 'GPU composite matrix transformation and rendering pipelines',
        caption:
          'Hardware accelerated CSS transform pipelines running at 120 FPS',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-gsap-smooth-motion',
      },
      {
        id: 'img-gsap-3',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        alt: 'Chrome DevTools rendering timeline and FPS benchmark graphs',
        caption:
          'Zero layout thrashing verification via Chrome performance profiles',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-gsap-smooth-motion',
      },
    ],
  },
  {
    id: 'blog-qa-automation-pipelines',
    slug: 'building-bulletproof-qa-pipelines-playwright-scandium',
    title:
      'Automated Quality Assurance: From Scandium & Playwright to CI/CD Release Gates',
    excerpt:
      'How to build deterministic automated testing pipelines that catch visual regressions, state corruption, and broken API contracts before they reach production.',
    content:
      "# Automated Quality Assurance: From Scandium & Playwright to CI/CD Release Gates\n\nQuality Assurance is often treated as the final phase before a release—a manual checklist run by exhausted developers late on a Friday evening. In reality, software quality is an engineering discipline that must be baked into every layer of your repository: from static type systems and unit contracts to headless browser end-to-end (E2E) suites.\n\nIn this deep dive, we explore the automated testing architecture we use to guarantee zero-defect releases across our web applications.\n\n![QA Automation and Test Engineering](https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. The Practical Testing Pyramid\n\nA healthy test suite balances execution speed, maintenance overhead, and failure isolation:\n\n1. **Static & Contract Layer**: TypeScript strict mode + Prisma schema validations verify data wire types at compile time.\n2. **Deterministic Integration Checks (`bun test`)**: Fast, in-memory checks verifying business rules, date parsers, token rotators, and authentication guards in under 2 seconds.\n3. **End-to-End Visual & Functional Suites (Playwright & Scandium)**: Real Chromium/WebKit instances validating entire user journeys (logging in, creating drafts, publishing articles, filtering tags).\n\n```typescript\n// Playwright E2E Admin Publishing Test\nimport { test, expect } from '@playwright/test';\n\ntest('admin can create and publish an article end-to-end', async ({ page }) => {\n  await page.goto('/admin-252755/login');\n  await page.fill('input[type=\"email\"]', 'admin@example.com');\n  await page.fill('input[type=\"password\"]', 'secure-password');\n  await page.click('button[type=\"submit\"]');\n\n  await expect(page).toHaveURL('/admin-252755');\n  await page.click('a[href=\"/admin-252755/blogs/new\"]');\n\n  await page.fill('input[name=\"title\"]', 'E2E Verified Article');\n  await page.fill('textarea[name=\"content\"]', '# Test Content\\n\\nVerified via Playwright.');\n  await page.click('button:has-text(\"Publish\")');\n\n  await expect(page.locator('.adm-notice.ok')).toBeVisible();\n});\n```\n\n![Automated Pipeline Dashboard](https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Preventing Flaky Tests with Deterministic Fixtures\n\nThe biggest enemy of automated testing is non-determinism (flakiness). Tests that pass 95% of the time and fail randomly destroy engineering confidence.\n\n### Strategies for Flake Elimination:\n- **Never rely on arbitrary `sleep(3000)`**: Always await specific DOM state assertions (`toBeVisible()`, `toHaveCount()`).\n- **Isolate Database State**: Run tests against isolated schema transactions or automatically seed sanitized sandbox datasets before each run.\n- **Mock External Third-Party APIs**: Intercept outbound payment, email, or analytics calls with deterministic MSW (Mock Service Worker) handlers.\n\n![CI/CD GitHub Actions Workflow](https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. GitHub Actions CI/CD Release Gates\n\nOur Turborepo pipelines fan out automated checks across parallel cloud runners on every Pull Request:\n1. **Linter & Formatting**: ESLint + Prettier check.\n2. **Typecheck**: Full `tsc --noEmit` validation across all monorepo packages.\n3. **Unit & Integration**: Fast Bun check execution.\n4. **Build & Bundle Analyzer**: Next.js production build verification ensuring bundle budgets stay under 150KB gzip.\n\nInvesting in rigorous QA pipelines gives engineering teams the superpower to deploy multiple times a day with complete peace of mind.",
    coverImage:
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    tags: ['QA', 'Testing', 'Playwright', 'DevOps', 'CI/CD'],
    published: true,
    featured: false,
    position: 5,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-02-05T13:20:00.000Z',
    updatedAt: '2026-02-05T13:20:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-qa-1',
        url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
        alt: 'Software testing code screen and debugging interface',
        caption: 'Automated test suite execution and continuous validation',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-qa-automation-pipelines',
      },
      {
        id: 'img-qa-2',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        alt: 'Quality metrics report and bug resolution telemetry',
        caption: 'Regression tracking and automated visual assertion coverage',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-qa-automation-pipelines',
      },
      {
        id: 'img-qa-3',
        url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        alt: 'Continuous integration cloud servers and pipeline automation',
        caption:
          'GitHub Actions release gates executing monorepo test matrices',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-qa-automation-pipelines',
      },
    ],
  },
  {
    id: 'blog-production-security',
    slug: 'production-security-nextjs-nestjs-defense-in-depth',
    title:
      'Production Security Architecture: HttpOnly Tokens, Throttling & CSRF Mitigation',
    excerpt:
      'A comprehensive guide to securing full-stack Next.js and NestJS applications using defense-in-depth, token family rotation, and rate limiting.',
    content:
      "# Production Security Architecture: HttpOnly Tokens, Throttling & CSRF Mitigation\n\nSecurity cannot be treated as an isolated plugin or an afterthought added just before launch. A single missing security header, an exposed JWT secret, or an unthrottled authentication endpoint can expose an entire user database or allow malicious attackers to hijack administrative sessions.\n\nIn this architecture guide, we review the layered defense-in-depth principles implemented across our NestJS API and Next.js frontend proxy.\n\n![Cybersecurity Shield and Digital Defense](https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. Secure Authentication: HttpOnly Cookies vs LocalStorage\n\nStoring JWT access tokens in browser `localStorage` is an anti-pattern. Any Cross-Site Scripting (XSS) vulnerability inside a third-party npm dependency can immediately read `localStorage.getItem('token')` and exfiltrate user credentials.\n\nWe implement double-cookie token rotation:\n- **Access Token (15-minute TTL)**: Stored in a `Secure`, `HttpOnly`, `SameSite=Lax` cookie named `pf_access`.\n- **Refresh Token (7-day TTL)**: Stored in a `Secure`, `HttpOnly`, `Path=/api/auth` cookie named `pf_refresh`.\n- **Token Family Rotation**: Whenever a refresh token is exchanged, a new token family hash is generated. If an old refresh token is reused, all active sessions for that user are revoked immediately (detecting token theft).\n\n```typescript\n// Cookie configuration in NestJS Authentication Service\nexport function setAuthCookies(res: Response, access: string, refresh: string) {\n  const isProd = process.env.NODE_ENV === 'production';\n\n  res.cookie('pf_access', access, {\n    httpOnly: true,\n    secure: isProd,\n    sameSite: 'lax',\n    maxAge: 15 * 60 * 1000,\n    path: '/',\n  });\n\n  res.cookie('pf_refresh', refresh, {\n    httpOnly: true,\n    secure: isProd,\n    sameSite: 'lax',\n    maxAge: 7 * 24 * 60 * 60 * 1000,\n    path: '/api/auth',\n  });\n}\n```\n\n![Security Token Rotation Flow](https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Global Rate Limiting & Denial of Service Protection\n\nTo protect against credential stuffing, brute force login attempts, and API scraping, we implement multi-tier rate limiting using `@nestjs/throttler`.\n\n```typescript\n// App Throttler Configuration\n@Module({\n  imports: [\n    ThrottlerModule.forRoot([\n      {\n        name: 'short',\n        ttl: 1000,\n        limit: 10, // Max 10 requests per second\n      },\n      {\n        name: 'medium',\n        ttl: 60000,\n        limit: 300, // Max 300 requests per minute\n      },\n    ]),\n  ],\n})\nexport class AppModule {}\n```\n\nSpecific high-risk endpoints (such as `/api/auth/login` and password resets) apply specialized guards allowing a maximum of 5 attempts every 15 minutes before locking IP addresses.\n\n![Cloud Security Monitoring](https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Strict HTTP Security Headers\n\nEvery HTTP response dispatched by Next.js and NestJS carries industry-standard defensive headers:\n- `Content-Security-Policy (CSP)`: Restricts script execution to trusted origins and nonces.\n- `X-Frame-Options: DENY`: Prevents clickjacking attacks by blocking iframe embedding.\n- `X-Content-Type-Options: nosniff`: Stops MIME-type sniffing.\n- `Referrer-Policy: strict-origin-when-cross-origin`: Prevents leaking private query paths in HTTP Referer headers.\n\nBuilding secure applications is an ongoing commitment to paranoia, automated validation, and continuous auditing.",
    coverImage:
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    tags: ['Security', 'NestJS', 'Next.js', 'Auth', 'Backend'],
    published: true,
    featured: false,
    position: 6,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-01-28T09:40:00.000Z',
    updatedAt: '2026-01-28T09:40:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-sec-1',
        url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
        alt: 'Digital lock and cybersecurity infrastructure',
        caption: 'Defense-in-depth architecture across API and frontend proxy',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-production-security',
      },
      {
        id: 'img-sec-2',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
        alt: 'Encrypted code stream and cryptographic key verification',
        caption: 'Token family rotation and HttpOnly cookie protections',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-production-security',
      },
      {
        id: 'img-sec-3',
        url: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80',
        alt: 'Server security operations center interface',
        caption: 'Rate limiting and DDoS mitigation telemetry',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-production-security',
      },
    ],
  },
  {
    id: 'blog-media-pipelines',
    slug: 'zero-egress-media-pipelines-supabase-storage',
    title:
      'Zero-Egress Media Architecture with Supabase Storage, Sharp & Next/Image',
    excerpt:
      'How to build high-performance image upload and transformation pipelines using presigned S3 URLs, edge CDN caching, and zero-egress architecture.',
    content:
      "# Zero-Egress Media Architecture with Supabase Storage, Sharp & Next/Image\n\nHandling user media uploads incorrectly can quickly ruin application performance and balloon cloud infrastructure bills. Streaming multi-megabyte image uploads through an API server consumes memory, ties up Node.js event loops, and incurs double egress costs (Client → API Server → S3 Storage Bucket).\n\nIn this article, we examine how we engineered a zero-egress media pipeline using Supabase Storage (S3-compatible API), Sharp image optimization, and Next.js `<Image>` edge transformations.\n\n![Cloud Storage and Media Infrastructure](https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. Direct Presigned Browser Uploads\n\nThe core philosophy of zero-egress architecture is simple: **the application server never handles raw image bytes**.\n\nInstead, the browser requests a cryptographically signed upload ticket from the backend and transfers the binary payload directly to object storage over HTTPS.\n\n```\n1. Browser → POST /api/storage/presign { filename: 'hero.png', mime: 'image/png' }\n2. API Server → Returns presigned S3 upload URL with 60-second expiration.\n3. Browser → Direct PUT request to Supabase S3 bucket.\n4. Browser → POST /api/media/confirm { storagePath, alt, width, height }\n```\n\n```typescript\n// Presign route handler in NestJS\n@Post('storage/presign')\n@UseGuards(JwtAuthGuard)\nasync getPresignedUploadUrl(@Body() dto: PresignDto) {\n  const extension = dto.filename.split('.').pop()?.toLowerCase() || 'webp';\n  const uniqueKey = `blogs/${dto.slug}/${uuidv4()}.${extension}`;\n\n  const { data, error } = await this.supabase.storage\n    .from('portfolio-storage')\n    .createSignedUploadUrl(uniqueKey);\n\n  if (error) throw new InternalServerErrorException(error.message);\n  return { signedUrl: data.signedUrl, path: data.path };\n}\n```\n\n![Image Transformation Processing](https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Client-Side Pre-Processing & WebP Compression\n\nBefore initiating an upload, high-resolution camera photos (often 12MB+ JPEGs) are normalized in a browser Web Worker using the OffscreenCanvas API:\n- Images are scaled down to a maximum width of **2400 pixels**.\n- Unnecessary EXIF metadata (GPS coordinates, camera serials) is stripped.\n- Images are encoded to WebP at 85% quality, reducing payload size by **75% to 90%** before transmission.\n\n![Edge CDN Distribution Map](https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Global Edge CDN Delivery & Next.js `<Image>`\n\nOnce stored in the bucket, images are delivered through a global CDN with `Cache-Control: public, max-age=31536000, immutable`. Next.js transforms assets on demand, generating responsive `srcset` variants in modern **AVIF** and **WebP** formats with automatic blur placeholders.\n\nThis setup achieves **100/100 Google Lighthouse media performance scores** while keeping server compute costs virtually at zero.",
    coverImage:
      'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Storage', 'Supabase', 'Next.js', 'Performance', 'Cloud'],
    published: true,
    featured: false,
    position: 7,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-01-20T11:15:00.000Z',
    updatedAt: '2026-01-20T11:15:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-media-1',
        url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',
        alt: 'Cloud data center storage servers and object storage pools',
        caption: 'Zero-egress direct S3 storage pipeline',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-media-pipelines',
      },
      {
        id: 'img-media-2',
        url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
        alt: 'High speed visual compression and WebP formatting metrics',
        caption: 'Client-side Web Worker image resizing and metadata stripping',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-media-pipelines',
      },
      {
        id: 'img-media-3',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        alt: 'Global CDN network edge caching node diagram',
        caption: 'Edge CDN distribution with immutable caching headers',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-media-pipelines',
      },
    ],
  },
  {
    id: 'blog-distributed-scheduler',
    slug: 'distributed-task-scheduling-postgresql-advisory-locks',
    title:
      'Distributed Task Scheduling in NestJS with PostgreSQL Advisory Locks',
    excerpt:
      'How to execute reliable, concurrency-safe cron jobs and scheduled article releases across multi-instance server clusters without distributed deadlocks.',
    content:
      "# Distributed Task Scheduling in NestJS with PostgreSQL Advisory Locks\n\nWhen scaling backend microservices across multiple container replicas (e.g., Kubernetes or AWS ECS), standard in-memory scheduling mechanisms like `@nestjs/schedule` or `node-cron` introduce dangerous concurrency bugs. Every running instance triggers the cron job simultaneously, causing duplicate invoice billing, duplicated emails, or race conditions during scheduled content publishing.\n\nIn this guide, we walk through building a resilient, distributed task scheduler using **PostgreSQL Session-Level Advisory Locks**.\n\n![Distributed Server Cluster](https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. What Are PostgreSQL Advisory Locks?\n\nUnlike table or row locks (`FOR UPDATE`), which lock concrete table records during transactions, PostgreSQL **Advisory Locks** are application-defined mutexes managed entirely in Postgres memory:\n- They are fast (zero disk I/O).\n- They can be non-blocking using `pg_try_advisory_lock(bigint)`.\n- If an instance acquires the lock, all other competing instances skip execution immediately rather than hanging in queue.\n\n```sql\n-- Non-blocking lock acquisition\nSELECT pg_try_advisory_lock(84920482019482); \n-- Returns true if lock acquired, false if another instance holds it\n```\n\n![Concurrency Control Workflow](https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Implementing the Distributed Scheduler Service\n\nHere is our production `BlogScheduler` implementation in NestJS, ensuring that scheduled articles are published exactly once across distributed server fleets:\n\n```typescript\nimport { Injectable, Logger } from '@nestjs/common';\nimport { Cron, CronExpression } from '@nestjs/schedule';\nimport { PrismaService } from '../prisma/prisma.service';\n\nconst SCHEDULER_LOCK_ID = 91827364528192n;\n\n@Injectable()\nexport class BlogScheduler {\n  private readonly logger = new Logger(BlogScheduler.name);\n\n  constructor(private prisma: PrismaService) {}\n\n  @Cron(CronExpression.EVERY_MINUTE)\n  async handleScheduledPublishing() {\n    // Attempt non-blocking distributed lock acquisition\n    const lock = await this.prisma.$queryRaw<{ acquired: boolean }[]>`\n      SELECT pg_try_advisory_lock(${SCHEDULER_LOCK_ID}) AS acquired\n    `;\n\n    if (!lock[0]?.acquired) {\n      this.logger.debug('Another instance is currently executing the publishing sweep.');\n      return;\n    }\n\n    try {\n      const now = new Date();\n      const duePosts = await this.prisma.blog.findMany({\n        where: {\n          status: 'SCHEDULED',\n          scheduledAt: { lte: now },\n        },\n      });\n\n      for (const post of duePosts) {\n        await this.prisma.blog.update({\n          where: { id: post.id },\n          data: {\n            status: 'PUBLISHED',\n            published: true,\n            publishedAt: now,\n          },\n        });\n        this.logger.log(`Successfully published scheduled article: \"${post.title}\"`);\n      }\n    } finally {\n      // Always release the lock in the finally block\n      await this.prisma.$queryRaw`SELECT pg_advisory_unlock(${SCHEDULER_LOCK_ID})`;\n    }\n  }\n}\n```\n\n![Automated Cron Job Telemetry](https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Failure Recovery and Exponential Backoff\n\nIf database connectivity drops during a scheduled sweep:\n1. The scheduler captures the failure and records an audit log with correlation IDs.\n2. It backs off exponentially (e.g., 30s, 60s, 120s) to prevent spamming a struggling database.\n3. Once connectivity recovers, all overdue articles published during the outage are processed safely in batch.\n\nPostgreSQL advisory locks provide an elegant, zero-dependency alternative to heavy distributed coordinator setups like Redis Redlock or Apache ZooKeeper.",
    coverImage:
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    tags: ['NestJS', 'PostgreSQL', 'Backend', 'Architecture', 'Concurrency'],
    published: true,
    featured: false,
    position: 8,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-01-12T08:00:00.000Z',
    updatedAt: '2026-01-12T08:00:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-sched-1',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        alt: 'Server rack infrastructure running distributed background tasks',
        caption:
          'Distributed background cron workers coordinated via PostgreSQL',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-distributed-scheduler',
      },
      {
        id: 'img-sched-2',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        alt: 'Task scheduler execution timeline and concurrency graphs',
        caption: 'Advisory lock acquisition and non-blocking mutex flow',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-distributed-scheduler',
      },
      {
        id: 'img-sched-3',
        url: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&w=1200&q=80',
        alt: 'System health monitoring dashboard and worker logs',
        caption: 'Scheduler recovery and exponential backoff telemetry',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-distributed-scheduler',
      },
    ],
  },
  {
    id: 'blog-design-systems-scale',
    slug: 'design-systems-that-scale-design-tokens-typography',
    title:
      'Designing Cohesive Design Systems: Tokens, Micro-Interactions & Fluid Typography',
    excerpt:
      'How to build consistent design systems across large web applications using CSS custom properties, clamp() typography, semantic color spaces, and haptic feedback.',
    content:
      '# Designing Cohesive Design Systems: Tokens, Micro-Interactions & Fluid Typography\n\nA great user interface is not the result of arbitrary CSS tweaks scattered across dozens of individual component stylesheets. Great software feels coherent because every margin, color tint, font size, and easing transition is derived from a unified, mathematical design system.\n\nIn this article, we break down how to structure modern design tokens, fluid clamp-based typography, and tactile micro-interactions in production web applications.\n\n![Design System Layout and Typography Tokens](https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 1. Mathematical Design Tokens with CSS Custom Properties\n\nDesign tokens are the fundamental visual constants of a digital brand. By organizing tokens into semantic layers, themes and dark mode physics adapt effortlessly:\n\n```css\n:root {\n  /* Primitive Palette */\n  --palette-paper: #faf8f5;\n  --palette-ink: #111215;\n  --palette-deep: #0c1829;\n  --palette-accent: #2e5a36;\n  --palette-highlight: #8ee9b1;\n\n  /* Semantic Application Tokens */\n  --paper: var(--palette-paper);\n  --ink: var(--palette-ink);\n  --deep: var(--palette-deep);\n  --accent: var(--palette-accent);\n  --highlight: var(--palette-highlight);\n  --line: rgba(17, 18, 21, 0.08);\n\n  /* Elevation & Shadows */\n  --shadow-sm: 0 2px 8px rgba(12, 24, 41, 0.04);\n  --shadow-md: 0 12px 32px rgba(12, 24, 41, 0.08);\n  --shadow-lg: 0 24px 64px rgba(12, 24, 41, 0.16);\n}\n```\n\n![Color Space and Contrast Ratios](https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 2. Fluid Typography with CSS `clamp()`\n\nFixed breakpoint font switches (`@media (max-width: 768px)`) create jarring jumps when resizing browser windows. With CSS `clamp()`, type scales smoothly across every screen width from mobile to 4K displays:\n\n```css\n/* Smooth fluid scaling between 375px and 1440px viewport widths */\nh1 {\n  font-size: clamp(32px, 5.5vw, 68px);\n  line-height: 1.1;\n  letter-spacing: -0.035em;\n  font-weight: 500;\n}\n\np.body-lead {\n  font-size: clamp(16px, 1.8vw, 21px);\n  line-height: 1.6;\n}\n```\n\n![Micro Interaction States and Focus Indicators](https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80)\n\n---\n\n## 3. Tactile Micro-Interactions & Focus Accessibility\n\nEvery interactive control should acknowledge user input through thoughtful micro-interactions:\n- **Button Presses**: Subtly compress by 1.5% (`transform: scale(0.985)`) on active press.\n- **Magnetic Buttons**: Drift gently toward cursor coordinates when hovered on desktop.\n- **Focus Rings**: Never remove `:focus`; always provide high-contrast `:focus-visible` outlines for keyboard navigation.\n\n```css\n.btn-tactile:focus-visible {\n  outline: 3px solid var(--accent);\n  outline-offset: 3px;\n}\n```\n\nA disciplined design system bridges the gap between engineering rigor and aesthetic beauty, turning everyday web tools into memorable software experiences.',
    coverImage:
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    tags: ['Design System', 'UI/UX', 'CSS', 'Typography', 'Frontend'],
    published: true,
    featured: false,
    position: 9,
    status: 'PUBLISHED',
    scheduledAt: null,
    publishedAt: '2026-01-05T15:00:00.000Z',
    updatedAt: '2026-01-05T15:00:00.000Z',
    linkedinUrl: 'https://www.linkedin.com/in/ashokabbhattaraii/',
    linkedinPostId: null,
    linkedinStatus: 'posted',
    images: [
      {
        id: 'img-ds-1',
        url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
        alt: 'Design system typography scale and component design tokens',
        caption: 'Mathematical design tokens and fluid typography scales',
        placement: 'COVER',
        position: 0,
        blogId: 'blog-design-systems-scale',
      },
      {
        id: 'img-ds-2',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
        alt: 'Color palette exploration and accessibility contrast ratios',
        caption: 'Semantic color spaces and WCAG AAA compliance',
        placement: 'INLINE',
        position: 1,
        blogId: 'blog-design-systems-scale',
      },
      {
        id: 'img-ds-3',
        url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
        alt: 'Interactive UI components and button micro-interaction states',
        caption:
          'Tactile interaction states and keyboard accessible focus rings',
        placement: 'GALLERY',
        position: 2,
        blogId: 'blog-design-systems-scale',
      },
    ],
  },
];
